# Generated by Django 2.2.5 on 2019-12-03 04:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dorm', max_length=50)),
                ('dorm_type', models.CharField(choices=[('FY', 'First Year'), ('UC', 'Upper Classmen')], default='FY', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(default='xx0xx', max_length=10)),
                ('staffer_type', models.CharField(choices=[('RA', 'Resident Advisor'), ('SR', 'Senior Resident')], default='RA', max_length=2)),
                ('name', models.CharField(default='Test Store', max_length=50)),
                ('on_coverage', models.BooleanField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coverage_tracker.Dorm')),
            ],
        ),
    ]
