# Generated by Django 2.2.5 on 2019-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0002_auto_20191202_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffer',
            name='building',
            field=models.CharField(default='Fake Dorm', max_length=100),
        ),
    ]
